In [4]:
import torch as th

In [15]:
def create_toy_data(num_goal_symbols, num_meas_symb, num_steps_top, num_steps_bot, N):
    goal = th.randint(0, num_goal_symbols, (N, num_steps_top))
    measures = th.randint(0, num_meas_symb, (N, num_steps_top))
    output = (goal*measures).unsqueeze(-1).repeat([1,1, num_steps_bot]).reshape([N, num_steps_top * num_steps_bot])
    measures = measures.unsqueeze(-1).repeat([1,1, num_steps_bot]).reshape([N, num_steps_top * num_steps_bot])
    return goal, measures, output

In [16]:
td_goals, td_measures, td_output = create_toy_data(num_goal_symbols=2, num_meas_symb=2, num_steps_top=3, num_steps_bot=3, N=4)

In [17]:
td_goals

tensor([[1, 0, 0],
        [1, 1, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [18]:
td_measures

tensor([[1, 1, 1, 0, 0, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [19]:
td_output

tensor([[1, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 1]])